GET http://localhost:8000/posts/

###
POST http://localhost:8000/posts/create
Content-Type: application/json

{
    "title": "title1",
    "description": "description1"
}


###
PATCH http://localhost:8000/posts/update/62480dc801f4aefc5ee80db8
Content-Type: application/json

{
    "title": "Hello",
    "description": "description1"
}

###
DELETE  http://localhost:8000/posts/delete/624d12de20f07708a92a2e72
###
PATCH   http://localhost:8000/posts/like/624d18ac61f4aa2cd0ede92c
