GET http://localhost:8000/posts/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNTI4OTYwNDA4ZTk1OTQyMDhhNzdhNCIsImlhdCI6MTY0OTY1MzkwMiwiZXhwIjoxNjQ5NjU3NTAyfQ.Jm3N52PPGJPQmYj_fTR0SNcjKfg03znApzDRFfzsXrU

###
POST http://localhost:8000/posts/create
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNTI4OTYwNDA4ZTk1OTQyMDhhNzdhNCIsImlhdCI6MTY0OTY1MzkwMiwiZXhwIjoxNjQ5NjU3NTAyfQ.Jm3N52PPGJPQmYj_fTR0SNcjKfg03znApzDRFfzsXrU
Content-Type: application/json

{
    "title": "title4",
    "description": "description4"
}


###
PATCH http://localhost:8000/posts/update/62480dc801f4aefc5ee80db8
Content-Type: application/json

{
    "title": "Hello",
    "description": "description1"
}

###
DELETE http://localhost:8000/posts/delete/624d12de20f07708a92a2e72
###
PATCH http://localhost:8000/posts/like/624d18ac61f4aa2cd0ede92c
###
POST http://localhost:8000/auth/signup
Content-Type: application/json

{
    "name": "johndoe",
    "email": "john2@doe.com",
    "password": "00000000",
    "confirmPassword": "00000000"
}
###
POST http://localhost:8000/auth/signin
Content-Type: application/json

{
    "email": "john2@doe.com",
    "password": "00000000"
}
###
POST http://localhost:8000/auth/refreshtoken
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNTI4OTYwNDA4ZTk1OTQyMDhhNzdhNCIsImlhdCI6MTY0OTY0NDcxMH0.5SSJGEib0XNFqAncGd2OuIx-EqWsGC6d82ma3teBqPU"
}
